ai2html_version: 0.65.6
project_type: undefined
tags: ai2html
min_width: 720
headline: "Ai Graphic Headline"
leadin: "This is a lead in to this diagram."
summary: ""
notes: "Notes: Text goes here."
sources: "Source: Michigan Engineering."
credit: "by U-M CoE"

